/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcceptRemoteClusterInviteRequest {
    #[serde(rename = "invite")]
    pub invite: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "default_team_id")]
    pub default_team_id: String,
    /// The password to decrypt the invite code.
    #[serde(rename = "password")]
    pub password: String,
}

impl AcceptRemoteClusterInviteRequest {
    pub fn new(invite: String, name: String, default_team_id: String, password: String) -> AcceptRemoteClusterInviteRequest {
        AcceptRemoteClusterInviteRequest {
            invite,
            name,
            display_name: None,
            default_team_id,
            password,
        }
    }
}

