/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRemoteClusterRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "default_team_id")]
    pub default_team_id: String,
    /// The password to use in the invite code. If empty, the server will generate one and it will be part of the response 
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl CreateRemoteClusterRequest {
    pub fn new(name: String, default_team_id: String) -> CreateRemoteClusterRequest {
        CreateRemoteClusterRequest {
            name,
            display_name: None,
            default_team_id,
            password: None,
        }
    }
}

