/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn).
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlaybookRequestChecklistsInnerItemsInner {
    /// The title of the checklist item.
    #[serde(rename = "title")]
    pub title: String,
    /// The slash command associated with this item. If the item has no slash command associated, this is an empty string
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// A detailed description of the checklist item, formatted with Markdown.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl CreatePlaybookRequestChecklistsInnerItemsInner {
    pub fn new(title: String) -> CreatePlaybookRequestChecklistsInnerItemsInner {
        CreatePlaybookRequestChecklistsInnerItemsInner {
            title,
            command: None,
            description: None,
        }
    }
}
