/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn).
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRemoteCluster201Response {
    #[serde(rename = "remote_cluster", skip_serializing_if = "Option::is_none")]
    pub remote_cluster: Option<Box<models::RemoteCluster>>,
    /// The encrypted invite for the newly created remote cluster
    #[serde(rename = "invite", skip_serializing_if = "Option::is_none")]
    pub invite: Option<String>,
    /// The password generated by the server if none was sent on the create request
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl CreateRemoteCluster201Response {
    pub fn new() -> CreateRemoteCluster201Response {
        CreateRemoteCluster201Response {
            remote_cluster: None,
            invite: None,
            password: None,
        }
    }
}
