/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn).
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvironmentConfigRateLimitSettings {
    #[serde(
        rename = "Enable",
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "bool_parser::deserialize_option_bool"
    )]
    pub enable: Option<bool>,
    #[serde(
        rename = "PerSec",
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "bool_parser::deserialize_option_bool"
    )]
    pub per_sec: Option<bool>,
    #[serde(
        rename = "MaxBurst",
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "bool_parser::deserialize_option_bool"
    )]
    pub max_burst: Option<bool>,
    #[serde(
        rename = "MemoryStoreSize",
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "bool_parser::deserialize_option_bool"
    )]
    pub memory_store_size: Option<bool>,
    #[serde(
        rename = "VaryByRemoteAddr",
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "bool_parser::deserialize_option_bool"
    )]
    pub vary_by_remote_addr: Option<bool>,
    #[serde(
        rename = "VaryByHeader",
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "bool_parser::deserialize_option_bool"
    )]
    pub vary_by_header: Option<bool>,
}

impl EnvironmentConfigRateLimitSettings {
    pub fn new() -> EnvironmentConfigRateLimitSettings {
        EnvironmentConfigRateLimitSettings {
            enable: None,
            per_sec: None,
            max_burst: None,
            memory_store_size: None,
            vary_by_remote_addr: None,
            vary_by_header: None,
        }
    }
}
