/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Installation {
    /// A unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "allowed_ip_ranges", skip_serializing_if = "Option::is_none")]
    pub allowed_ip_ranges: Option<Box<models::AllowedIpRange>>,
    /// The current state of the installation
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}

impl Installation {
    pub fn new() -> Installation {
        Installation {
            id: None,
            allowed_ip_ranges: None,
            state: None,
        }
    }
}

