/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn).
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutgoingOAuthConnectionGetItem {
    /// The unique identifier for the outgoing OAuth connection.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of the outgoing OAuth connection.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The time in milliseconds the outgoing OAuth connection was created.
    #[serde(rename = "create_at", skip_serializing_if = "Option::is_none")]
    pub create_at: Option<i64>,
    /// The time in milliseconds the outgoing OAuth connection was last updated.
    #[serde(rename = "update_at", skip_serializing_if = "Option::is_none")]
    pub update_at: Option<i64>,
    /// The grant type of the outgoing OAuth connection.
    #[serde(rename = "grant_type", skip_serializing_if = "Option::is_none")]
    pub grant_type: Option<String>,
    /// The audiences of the outgoing OAuth connection.
    #[serde(rename = "audiences", skip_serializing_if = "Option::is_none")]
    pub audiences: Option<String>,
}

impl OutgoingOAuthConnectionGetItem {
    pub fn new() -> OutgoingOAuthConnectionGetItem {
        OutgoingOAuthConnectionGetItem {
            id: None,
            name: None,
            create_at: None,
            update_at: None,
            grant_type: None,
            audiences: None,
        }
    }
}
