/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutgoingOAuthConnectionPostItem {
    /// The name of the outgoing OAuth connection.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The client ID of the outgoing OAuth connection.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// The client secret of the outgoing OAuth connection.
    #[serde(rename = "client_secret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    /// The username of the credentials of the outgoing OAuth connection.
    #[serde(rename = "credentials_username", skip_serializing_if = "Option::is_none")]
    pub credentials_username: Option<String>,
    /// The password of the credentials of the outgoing OAuth connection.
    #[serde(rename = "credentials_password", skip_serializing_if = "Option::is_none")]
    pub credentials_password: Option<String>,
    /// The OAuth token URL of the outgoing OAuth connection.
    #[serde(rename = "oauth_token_url", skip_serializing_if = "Option::is_none")]
    pub oauth_token_url: Option<String>,
    /// The grant type of the outgoing OAuth connection.
    #[serde(rename = "grant_type", skip_serializing_if = "Option::is_none")]
    pub grant_type: Option<String>,
    /// The audiences of the outgoing OAuth connection.
    #[serde(rename = "audiences", skip_serializing_if = "Option::is_none")]
    pub audiences: Option<String>,
}

impl OutgoingOAuthConnectionPostItem {
    pub fn new() -> OutgoingOAuthConnectionPostItem {
        OutgoingOAuthConnectionPostItem {
            name: None,
            client_id: None,
            client_secret: None,
            credentials_username: None,
            credentials_password: None,
            oauth_token_url: None,
            grant_type: None,
            audiences: None,
        }
    }
}

