/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn).
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchRemoteClusterRequest {
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The team where channels from invites are created
    #[serde(rename = "default_team_id", skip_serializing_if = "Option::is_none")]
    pub default_team_id: Option<String>,
}

impl PatchRemoteClusterRequest {
    pub fn new() -> PatchRemoteClusterRequest {
        PatchRemoteClusterRequest {
            display_name: None,
            default_team_id: None,
        }
    }
}
