/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerLimits {
    /// The maximum number of users allowed on server
    #[serde(rename = "maxUsersLimit", skip_serializing_if = "Option::is_none")]
    pub max_users_limit: Option<i64>,
    /// The number of active users in the server
    #[serde(rename = "activeUserCount", skip_serializing_if = "Option::is_none")]
    pub active_user_count: Option<i64>,
}

impl ServerLimits {
    pub fn new() -> ServerLimits {
        ServerLimits {
            max_users_limit: None,
            active_user_count: None,
        }
    }
}

