/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusRequest {
    /// The status update message.
    #[serde(rename = "message")]
    pub message: String,
    /// The number of seconds until the system will send a reminder to the owner to update the status. No reminder will be scheduled if reminder is 0 or omitted.
    #[serde(rename = "reminder", skip_serializing_if = "Option::is_none")]
    pub reminder: Option<f64>,
}

impl StatusRequest {
    pub fn new(message: String) -> StatusRequest {
        StatusRequest {
            message,
            reminder: None,
        }
    }
}

