/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateChannelBookmarkRequest {
    /// The ID of the file associated with the channel bookmark. Required for bookmarks of type 'file'
    #[serde(rename = "file_id", skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
    /// The name of the channel bookmark
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The order of the channel bookmark
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<i64>,
    /// The URL associated with the channel bookmark. Required for type bookmarks of type 'link'
    #[serde(rename = "link_url", skip_serializing_if = "Option::is_none")]
    pub link_url: Option<String>,
    /// The URL of the image associated with the channel bookmark
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// The emoji of the channel bookmark
    #[serde(rename = "emoji", skip_serializing_if = "Option::is_none")]
    pub emoji: Option<String>,
    /// * `link` for channel bookmarks that reference a link. `link_url` is requied * `file` for channel bookmarks that reference a file. `file_id` is required 
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl UpdateChannelBookmarkRequest {
    pub fn new() -> UpdateChannelBookmarkRequest {
        UpdateChannelBookmarkRequest {
            file_id: None,
            display_name: None,
            sort_order: None,
            link_url: None,
            image_url: None,
            emoji: None,
            r#type: None,
        }
    }
}
/// * `link` for channel bookmarks that reference a link. `link_url` is requied * `file` for channel bookmarks that reference a file. `file_id` is required 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "link")]
    Link,
    #[serde(rename = "file")]
    File,
}

impl Default for Type {
    fn default() -> Type {
        Self::Link
    }
}

