/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateChannelBookmarkResponse {
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<Box<models::ChannelBookmarkWithFileInfo>>,
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<Box<models::ChannelBookmarkWithFileInfo>>,
}

impl UpdateChannelBookmarkResponse {
    pub fn new() -> UpdateChannelBookmarkResponse {
        UpdateChannelBookmarkResponse {
            updated: None,
            deleted: None,
        }
    }
}

