/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateJobStatusRequest {
    /// The status you want to set
    #[serde(rename = "status")]
    pub status: String,
    /// Set this to true to bypass status restrictions
    #[serde(rename = "force", skip_serializing_if = "Option::is_none", default, deserialize_with = "bool_parser::deserialize_option_bool")]
    pub force: Option<bool>,
}

impl UpdateJobStatusRequest {
    pub fn new(status: String) -> UpdateJobStatusRequest {
        UpdateJobStatusRequest {
            status,
            force: None,
        }
    }
}

