[package]
name = "mmrag"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
openai-api-rs = "5.0.13"
tokio = "1.41.0"
typify = "0.2.0"

mattermost_api = { workspace = true }
mattermost_bot = { workspace = true }
